### ISSUE TITLE
What about planner.js ?

### ISSUE THREAD

**Issue by Ugarz** [mlsen/raidcomp#1]
Hi,
First, I'd like to thank you providing this repo' I was looking for something like that and it's a kind of magic !
## Starting server

So if I get it right, running `node server.js` launch the chat app, but what about the "raid composer" ?
What am I doing wrong ?

**Comment by xmyno** [comment]
Hey.

I have no idea what you mean with planner.js or chat app.
This is a tool to form raid groups for World of Warcraft (and it's far from finished, therefore the lack of description). See http://raidcomp.mlsn.me.

If this is still the thing you were looking for: the project is set up to be run with Docker - see `docker-compose.prod.yml`. This automatically runs nginx, a mongo db server and the front- and backend of the project.

**Comment by Ugarz** [comment]
Sorry about that.
I was looking for a solution and browsing repositories I messed up mixing yours and another.
Besides your solution seems very smooth I like the way you create a Raid. I was looking at the manual of Docker you made me discover it :+1:
